// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: peer/chaincode_shim.proto
// </auto-generated>
// Original file comments:
//
// Copyright IBM Corp. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
#pragma warning disable 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Chaincode.NET.Protos {
  /// <summary>
  /// Interface that provides support to chaincode execution. ChaincodeContext
  /// provides the context necessary for the server to respond appropriately.
  /// </summary>
  public static partial class ChaincodeSupport
  {
    static readonly string __ServiceName = "protos.ChaincodeSupport";

    static readonly grpc::Marshaller<global::Chaincode.NET.Protos.ChaincodeMessage> __Marshaller_ChaincodeMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Chaincode.NET.Protos.ChaincodeMessage.Parser.ParseFrom);

    static readonly grpc::Method<global::Chaincode.NET.Protos.ChaincodeMessage, global::Chaincode.NET.Protos.ChaincodeMessage> __Method_Register = new grpc::Method<global::Chaincode.NET.Protos.ChaincodeMessage, global::Chaincode.NET.Protos.ChaincodeMessage>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Register",
        __Marshaller_ChaincodeMessage,
        __Marshaller_ChaincodeMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Chaincode.NET.Protos.ChaincodeShimReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ChaincodeSupport</summary>
    public abstract partial class ChaincodeSupportBase
    {
      public virtual global::System.Threading.Tasks.Task Register(grpc::IAsyncStreamReader<global::Chaincode.NET.Protos.ChaincodeMessage> requestStream, grpc::IServerStreamWriter<global::Chaincode.NET.Protos.ChaincodeMessage> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ChaincodeSupport</summary>
    public partial class ChaincodeSupportClient : grpc::ClientBase<ChaincodeSupportClient>
    {
      /// <summary>Creates a new client for ChaincodeSupport</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ChaincodeSupportClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ChaincodeSupport that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ChaincodeSupportClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ChaincodeSupportClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ChaincodeSupportClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Chaincode.NET.Protos.ChaincodeMessage, global::Chaincode.NET.Protos.ChaincodeMessage> Register(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Register(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Chaincode.NET.Protos.ChaincodeMessage, global::Chaincode.NET.Protos.ChaincodeMessage> Register(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Register, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ChaincodeSupportClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ChaincodeSupportClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ChaincodeSupportBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Register, serviceImpl.Register).Build();
    }

  }
}
#endregion
