// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: token/expectations.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Chaincode.NET.Protos {

  /// <summary>Holder for reflection information generated from token/expectations.proto</summary>
  public static partial class ExpectationsReflection {

    #region Descriptor
    /// <summary>File descriptor for token/expectations.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExpectationsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chh0b2tlbi9leHBlY3RhdGlvbnMucHJvdG8SBnByb3RvcxofZ29vZ2xlL3By",
            "b3RvYnVmL3RpbWVzdGFtcC5wcm90bxoXdG9rZW4vdHJhbnNhY3Rpb24ucHJv",
            "dG8iWAoQVG9rZW5FeHBlY3RhdGlvbhI1ChFwbGFpbl9leHBlY3RhdGlvbhgB",
            "IAEoCzIYLnByb3Rvcy5QbGFpbkV4cGVjdGF0aW9uSABCDQoLRXhwZWN0YXRp",
            "b24imQEKEFBsYWluRXhwZWN0YXRpb24SOwoSaW1wb3J0X2V4cGVjdGF0aW9u",
            "GAEgASgLMh0ucHJvdG9zLlBsYWluVG9rZW5FeHBlY3RhdGlvbkgAEj0KFHRy",
            "YW5zZmVyX2V4cGVjdGF0aW9uGAIgASgLMh0ucHJvdG9zLlBsYWluVG9rZW5F",
            "eHBlY3RhdGlvbkgAQgkKB3BheWxvYWQiNgoVUGxhaW5Ub2tlbkV4cGVjdGF0",
            "aW9uEh0KB291dHB1dHMYASADKAsyDC5QbGFpbk91dHB1dEJoCiNvcmcuaHlw",
            "ZXJsZWRnZXIuZmFicmljLnByb3Rvcy50b2tlbloqZ2l0aHViLmNvbS9oeXBl",
            "cmxlZGdlci9mYWJyaWMvcHJvdG9zL3Rva2VuqgIUQ2hhaW5jb2RlLk5FVC5Q",
            "cm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Chaincode.NET.Protos.TransactionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Chaincode.NET.Protos.TokenExpectation), global::Chaincode.NET.Protos.TokenExpectation.Parser, new[]{ "PlainExpectation" }, new[]{ "Expectation" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chaincode.NET.Protos.PlainExpectation), global::Chaincode.NET.Protos.PlainExpectation.Parser, new[]{ "ImportExpectation", "TransferExpectation" }, new[]{ "Payload" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chaincode.NET.Protos.PlainTokenExpectation), global::Chaincode.NET.Protos.PlainTokenExpectation.Parser, new[]{ "Outputs" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// TokenExpectation represent the belief that someone should achieve in terms of a token action
  /// </summary>
  public sealed partial class TokenExpectation : pb::IMessage<TokenExpectation> {
    private static readonly pb::MessageParser<TokenExpectation> _parser = new pb::MessageParser<TokenExpectation>(() => new TokenExpectation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TokenExpectation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chaincode.NET.Protos.ExpectationsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TokenExpectation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TokenExpectation(TokenExpectation other) : this() {
      switch (other.ExpectationCase) {
        case ExpectationOneofCase.PlainExpectation:
          PlainExpectation = other.PlainExpectation.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TokenExpectation Clone() {
      return new TokenExpectation(this);
    }

    /// <summary>Field number for the "plain_expectation" field.</summary>
    public const int PlainExpectationFieldNumber = 1;
    /// <summary>
    /// PlainExpectation describes a plain token expectation
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Chaincode.NET.Protos.PlainExpectation PlainExpectation {
      get { return expectationCase_ == ExpectationOneofCase.PlainExpectation ? (global::Chaincode.NET.Protos.PlainExpectation) expectation_ : null; }
      set {
        expectation_ = value;
        expectationCase_ = value == null ? ExpectationOneofCase.None : ExpectationOneofCase.PlainExpectation;
      }
    }

    private object expectation_;
    /// <summary>Enum of possible cases for the "Expectation" oneof.</summary>
    public enum ExpectationOneofCase {
      None = 0,
      PlainExpectation = 1,
    }
    private ExpectationOneofCase expectationCase_ = ExpectationOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExpectationOneofCase ExpectationCase {
      get { return expectationCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearExpectation() {
      expectationCase_ = ExpectationOneofCase.None;
      expectation_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TokenExpectation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TokenExpectation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PlainExpectation, other.PlainExpectation)) return false;
      if (ExpectationCase != other.ExpectationCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (expectationCase_ == ExpectationOneofCase.PlainExpectation) hash ^= PlainExpectation.GetHashCode();
      hash ^= (int) expectationCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (expectationCase_ == ExpectationOneofCase.PlainExpectation) {
        output.WriteRawTag(10);
        output.WriteMessage(PlainExpectation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (expectationCase_ == ExpectationOneofCase.PlainExpectation) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlainExpectation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TokenExpectation other) {
      if (other == null) {
        return;
      }
      switch (other.ExpectationCase) {
        case ExpectationOneofCase.PlainExpectation:
          if (PlainExpectation == null) {
            PlainExpectation = new global::Chaincode.NET.Protos.PlainExpectation();
          }
          PlainExpectation.MergeFrom(other.PlainExpectation);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Chaincode.NET.Protos.PlainExpectation subBuilder = new global::Chaincode.NET.Protos.PlainExpectation();
            if (expectationCase_ == ExpectationOneofCase.PlainExpectation) {
              subBuilder.MergeFrom(PlainExpectation);
            }
            input.ReadMessage(subBuilder);
            PlainExpectation = subBuilder;
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// PlainExpectation represent the plain expectation where no confidentiality is provided.
  /// </summary>
  public sealed partial class PlainExpectation : pb::IMessage<PlainExpectation> {
    private static readonly pb::MessageParser<PlainExpectation> _parser = new pb::MessageParser<PlainExpectation>(() => new PlainExpectation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlainExpectation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chaincode.NET.Protos.ExpectationsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlainExpectation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlainExpectation(PlainExpectation other) : this() {
      switch (other.PayloadCase) {
        case PayloadOneofCase.ImportExpectation:
          ImportExpectation = other.ImportExpectation.Clone();
          break;
        case PayloadOneofCase.TransferExpectation:
          TransferExpectation = other.TransferExpectation.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlainExpectation Clone() {
      return new PlainExpectation(this);
    }

    /// <summary>Field number for the "import_expectation" field.</summary>
    public const int ImportExpectationFieldNumber = 1;
    /// <summary>
    /// ImportExpectation describes an token import expectation
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Chaincode.NET.Protos.PlainTokenExpectation ImportExpectation {
      get { return payloadCase_ == PayloadOneofCase.ImportExpectation ? (global::Chaincode.NET.Protos.PlainTokenExpectation) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ImportExpectation;
      }
    }

    /// <summary>Field number for the "transfer_expectation" field.</summary>
    public const int TransferExpectationFieldNumber = 2;
    /// <summary>
    /// TransferExpectation describes a token transfer expectation
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Chaincode.NET.Protos.PlainTokenExpectation TransferExpectation {
      get { return payloadCase_ == PayloadOneofCase.TransferExpectation ? (global::Chaincode.NET.Protos.PlainTokenExpectation) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.TransferExpectation;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      ImportExpectation = 1,
      TransferExpectation = 2,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlainExpectation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlainExpectation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ImportExpectation, other.ImportExpectation)) return false;
      if (!object.Equals(TransferExpectation, other.TransferExpectation)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (payloadCase_ == PayloadOneofCase.ImportExpectation) hash ^= ImportExpectation.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.TransferExpectation) hash ^= TransferExpectation.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (payloadCase_ == PayloadOneofCase.ImportExpectation) {
        output.WriteRawTag(10);
        output.WriteMessage(ImportExpectation);
      }
      if (payloadCase_ == PayloadOneofCase.TransferExpectation) {
        output.WriteRawTag(18);
        output.WriteMessage(TransferExpectation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (payloadCase_ == PayloadOneofCase.ImportExpectation) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ImportExpectation);
      }
      if (payloadCase_ == PayloadOneofCase.TransferExpectation) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TransferExpectation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlainExpectation other) {
      if (other == null) {
        return;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.ImportExpectation:
          if (ImportExpectation == null) {
            ImportExpectation = new global::Chaincode.NET.Protos.PlainTokenExpectation();
          }
          ImportExpectation.MergeFrom(other.ImportExpectation);
          break;
        case PayloadOneofCase.TransferExpectation:
          if (TransferExpectation == null) {
            TransferExpectation = new global::Chaincode.NET.Protos.PlainTokenExpectation();
          }
          TransferExpectation.MergeFrom(other.TransferExpectation);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Chaincode.NET.Protos.PlainTokenExpectation subBuilder = new global::Chaincode.NET.Protos.PlainTokenExpectation();
            if (payloadCase_ == PayloadOneofCase.ImportExpectation) {
              subBuilder.MergeFrom(ImportExpectation);
            }
            input.ReadMessage(subBuilder);
            ImportExpectation = subBuilder;
            break;
          }
          case 18: {
            global::Chaincode.NET.Protos.PlainTokenExpectation subBuilder = new global::Chaincode.NET.Protos.PlainTokenExpectation();
            if (payloadCase_ == PayloadOneofCase.TransferExpectation) {
              subBuilder.MergeFrom(TransferExpectation);
            }
            input.ReadMessage(subBuilder);
            TransferExpectation = subBuilder;
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// PlainTokenExpectation represents the expecation that
  /// certain outputs will be matched
  /// </summary>
  public sealed partial class PlainTokenExpectation : pb::IMessage<PlainTokenExpectation> {
    private static readonly pb::MessageParser<PlainTokenExpectation> _parser = new pb::MessageParser<PlainTokenExpectation>(() => new PlainTokenExpectation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlainTokenExpectation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chaincode.NET.Protos.ExpectationsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlainTokenExpectation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlainTokenExpectation(PlainTokenExpectation other) : this() {
      outputs_ = other.outputs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlainTokenExpectation Clone() {
      return new PlainTokenExpectation(this);
    }

    /// <summary>Field number for the "outputs" field.</summary>
    public const int OutputsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Chaincode.NET.Protos.PlainOutput> _repeated_outputs_codec
        = pb::FieldCodec.ForMessage(10, global::Chaincode.NET.Protos.PlainOutput.Parser);
    private readonly pbc::RepeatedField<global::Chaincode.NET.Protos.PlainOutput> outputs_ = new pbc::RepeatedField<global::Chaincode.NET.Protos.PlainOutput>();
    /// <summary>
    /// Outputs contains the expected outputs
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Chaincode.NET.Protos.PlainOutput> Outputs {
      get { return outputs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlainTokenExpectation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlainTokenExpectation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!outputs_.Equals(other.outputs_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= outputs_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      outputs_.WriteTo(output, _repeated_outputs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += outputs_.CalculateSize(_repeated_outputs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlainTokenExpectation other) {
      if (other == null) {
        return;
      }
      outputs_.Add(other.outputs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            outputs_.AddEntriesFrom(input, _repeated_outputs_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
