// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peer/chaincode_event.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos {

  /// <summary>Holder for reflection information generated from peer/chaincode_event.proto</summary>
  public static partial class ChaincodeEventReflection {

    #region Descriptor
    /// <summary>File descriptor for peer/chaincode_event.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChaincodeEventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpwZWVyL2NoYWluY29kZV9ldmVudC5wcm90bxIGcHJvdG9zIloKDkNoYWlu",
            "Y29kZUV2ZW50EhQKDGNoYWluY29kZV9pZBgBIAEoCRINCgV0eF9pZBgCIAEo",
            "CRISCgpldmVudF9uYW1lGAMgASgJEg8KB3BheWxvYWQYBCABKAxCZgoib3Jn",
            "Lmh5cGVybGVkZ2VyLmZhYnJpYy5wcm90b3MucGVlckIVQ2hhaW5jb2RlRXZl",
            "bnRQYWNrYWdlWilnaXRodWIuY29tL2h5cGVybGVkZ2VyL2ZhYnJpYy9wcm90",
            "b3MvcGVlcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.ChaincodeEvent), global::Protos.ChaincodeEvent.Parser, new[]{ "ChaincodeId", "TxId", "EventName", "Payload" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///ChaincodeEvent is used for events and registrations that are specific to chaincode
  ///string type - "chaincode"
  /// </summary>
  public sealed partial class ChaincodeEvent : pb::IMessage<ChaincodeEvent> {
    private static readonly pb::MessageParser<ChaincodeEvent> _parser = new pb::MessageParser<ChaincodeEvent>(() => new ChaincodeEvent());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChaincodeEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.ChaincodeEventReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChaincodeEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChaincodeEvent(ChaincodeEvent other) : this() {
      chaincodeId_ = other.chaincodeId_;
      txId_ = other.txId_;
      eventName_ = other.eventName_;
      payload_ = other.payload_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChaincodeEvent Clone() {
      return new ChaincodeEvent(this);
    }

    /// <summary>Field number for the "chaincode_id" field.</summary>
    public const int ChaincodeIdFieldNumber = 1;
    private string chaincodeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ChaincodeId {
      get { return chaincodeId_; }
      set {
        chaincodeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tx_id" field.</summary>
    public const int TxIdFieldNumber = 2;
    private string txId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TxId {
      get { return txId_; }
      set {
        txId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "event_name" field.</summary>
    public const int EventNameFieldNumber = 3;
    private string eventName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EventName {
      get { return eventName_; }
      set {
        eventName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 4;
    private pb::ByteString payload_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Payload {
      get { return payload_; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChaincodeEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChaincodeEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChaincodeId != other.ChaincodeId) return false;
      if (TxId != other.TxId) return false;
      if (EventName != other.EventName) return false;
      if (Payload != other.Payload) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ChaincodeId.Length != 0) hash ^= ChaincodeId.GetHashCode();
      if (TxId.Length != 0) hash ^= TxId.GetHashCode();
      if (EventName.Length != 0) hash ^= EventName.GetHashCode();
      if (Payload.Length != 0) hash ^= Payload.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ChaincodeId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ChaincodeId);
      }
      if (TxId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TxId);
      }
      if (EventName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EventName);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Payload);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ChaincodeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChaincodeId);
      }
      if (TxId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TxId);
      }
      if (EventName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EventName);
      }
      if (Payload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChaincodeEvent other) {
      if (other == null) {
        return;
      }
      if (other.ChaincodeId.Length != 0) {
        ChaincodeId = other.ChaincodeId;
      }
      if (other.TxId.Length != 0) {
        TxId = other.TxId;
      }
      if (other.EventName.Length != 0) {
        EventName = other.EventName;
      }
      if (other.Payload.Length != 0) {
        Payload = other.Payload;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            ChaincodeId = input.ReadString();
            break;
          }
          case 18: {
            TxId = input.ReadString();
            break;
          }
          case 26: {
            EventName = input.ReadString();
            break;
          }
          case 34: {
            Payload = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
